package com.jigsaw.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSiteUser<M extends BaseSiteUser<M>> extends Model<M> implements IBean {

	public void setUserID(java.lang.Integer UserID) {
		set("UserID", UserID);
	}

	public java.lang.Integer getUserID() {
		return get("UserID");
	}

	public void setLoginName(java.lang.String LoginName) {
		set("LoginName", LoginName);
	}

	public java.lang.String getLoginName() {
		return get("LoginName");
	}

	public void setRealName(java.lang.String RealName) {
		set("RealName", RealName);
	}

	public java.lang.String getRealName() {
		return get("RealName");
	}

	public void setPassWord(java.lang.String PassWord) {
		set("PassWord", PassWord);
	}

	public java.lang.String getPassWord() {
		return get("PassWord");
	}

	public void setEmail(java.lang.String Email) {
		set("Email", Email);
	}

	public java.lang.String getEmail() {
		return get("Email");
	}

	public void setTelphone(java.lang.String Telphone) {
		set("Telphone", Telphone);
	}

	public java.lang.String getTelphone() {
		return get("Telphone");
	}

	public void setIsSysAccount(java.lang.Integer IsSysAccount) {
		set("IsSysAccount", IsSysAccount);
	}

	public java.lang.Integer getIsSysAccount() {
		return get("IsSysAccount");
	}

	public void setOfficeTelphone(java.lang.String OfficeTelphone) {
		set("OfficeTelphone", OfficeTelphone);
	}

	public java.lang.String getOfficeTelphone() {
		return get("OfficeTelphone");
	}

	public void setMobilePhone(java.lang.String MobilePhone) {
		set("MobilePhone", MobilePhone);
	}

	public java.lang.String getMobilePhone() {
		return get("MobilePhone");
	}

	public void setDescription(java.lang.String Description) {
		set("Description", Description);
	}

	public java.lang.String getDescription() {
		return get("Description");
	}

	public void setStatus(java.lang.Integer Status) {
		set("Status", Status);
	}

	public java.lang.Integer getStatus() {
		return get("Status");
	}

	public void setOrganizationID(java.lang.Integer OrganizationID) {
		set("OrganizationID", OrganizationID);
	}

	public java.lang.Integer getOrganizationID() {
		return get("OrganizationID");
	}

	public void setDepartmentID(java.lang.Integer DepartmentID) {
		set("DepartmentID", DepartmentID);
	}

	public java.lang.Integer getDepartmentID() {
		return get("DepartmentID");
	}

	public void setCreator(java.lang.String Creator) {
		set("Creator", Creator);
	}

	public java.lang.String getCreator() {
		return get("Creator");
	}

	public void setCreateTime(java.util.Date CreateTime) {
		set("CreateTime", CreateTime);
	}

	public java.util.Date getCreateTime() {
		return get("CreateTime");
	}

	public void setModifier(java.lang.String Modifier) {
		set("Modifier", Modifier);
	}

	public java.lang.String getModifier() {
		return get("Modifier");
	}

	public void setModifyTime(java.util.Date ModifyTime) {
		set("ModifyTime", ModifyTime);
	}

	public java.util.Date getModifyTime() {
		return get("ModifyTime");
	}

	public void setPhotoUrl(java.lang.String PhotoUrl) {
		set("PhotoUrl", PhotoUrl);
	}

	public java.lang.String getPhotoUrl() {
		return get("PhotoUrl");
	}

	public void setSexTypeID(java.lang.Integer SexTypeID) {
		set("SexTypeID", SexTypeID);
	}

	public java.lang.Integer getSexTypeID() {
		return get("SexTypeID");
	}

	public void setBirthday(java.util.Date Birthday) {
		set("Birthday", Birthday);
	}

	public java.util.Date getBirthday() {
		return get("Birthday");
	}

	public void setIdentity(java.lang.String Identity) {
		set("Identity", Identity);
	}

	public java.lang.String getIdentity() {
		return get("Identity");
	}

	public void setPoliticsTypeID(java.lang.Integer PoliticsTypeID) {
		set("PoliticsTypeID", PoliticsTypeID);
	}

	public java.lang.Integer getPoliticsTypeID() {
		return get("PoliticsTypeID");
	}

	public void setTitleName(java.lang.String TitleName) {
		set("TitleName", TitleName);
	}

	public java.lang.String getTitleName() {
		return get("TitleName");
	}

}
