package com.jigsaw.model;

import com.jigsaw.model.base.BasePassportSigninInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PassportSigninInfo extends BasePassportSigninInfo<PassportSigninInfo> {
	public static final PassportSigninInfo dao = new PassportSigninInfo();
}
