package com.jigsaw.model;

import java.sql.SQLException;
import java.util.Date;
import java.util.List;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.IAtom;
import com.jfinal.plugin.activerecord.Record;
import com.jigsaw.model.base.BasePassportUseraccesslog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PassportUseraccesslog extends BasePassportUseraccesslog<PassportUseraccesslog> {
	public static final PassportUseraccesslog dao = new PassportUseraccesslog();
	
	public PassportUseraccesslog getAccessLog(int userId){
		List<PassportUseraccesslog> logs = dao.find(String.format("SELECT * FROM Passport_UserAccessLog WHERE UserID = %d", userId));
		if(logs.size() >= 1)
			return logs.get(0);
		return null;
	}
	
	public boolean saveAccessLog(int userId){
		boolean succeed = Db.tx(new IAtom() {
			
			@Override
			public boolean run() throws SQLException {
				List<Record> lst = Db.find("SELECT * FROM Passport_UserAccessLog WHERE UserID = ?", userId);
				if(lst.size() > 0){
					Record log = lst.get(0);
					Date lastLoginDate = log.getDate("LastLoginDate");
					int failCount = log.getInt("FailedPasswordAttemptCount");
					Date fail = log.getDate("FailedPasswordAttemptStart");
				}
				
				return false;
			}
		});
		
		return succeed;
	}
}
