package com.jigsaw.model;

import com.jigsaw.model.base.BasePassportTicket;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PassportTicket extends BasePassportTicket<PassportTicket> {
	public static final PassportTicket dao = new PassportTicket();
	
	public PassportTicket getById(String token){
		return dao.findById(token);
		
	}
	
	public String AppEnvironment;
	public java.lang.String getAppEnvironment() {
		return AppEnvironment;
	}
	public void setAppEnvironment(java.lang.String appEnvironment) {
		AppEnvironment = appEnvironment;
	}
}
