package com.jigsaw.model;

import java.util.Date;
import java.util.UUID;

import javax.servlet.http.HttpServletRequest;

import com.jigsaw.model.base.BasePassportSigninInfo;
import com.mysql.jdbc.StringUtils;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PassportSigninInfo extends BasePassportSigninInfo<PassportSigninInfo> {
	public static final PassportSigninInfo dao = new PassportSigninInfo();

	public PassportSigninInfo persistentSignIn(SiteUser userInfo, boolean bDontSaveUserId, boolean bAutoSignIn){
        
		String id = UUID.randomUUID().toString();
		dao.set("SIGNIN_ID", id)
		.set("USER_ID", userInfo.getUserID())
		.set("USER_NAME", userInfo.currentLoginName)
		.set("AUTHENTICATE_SERVER", userInfo.authServer)
		.save();
		
		return dao.findById(id);
	}
}
