package com.jigsaw.model;

import java.sql.SQLException;
import java.util.Date;
import java.util.List;

import javax.servlet.http.HttpServletRequest;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.IAtom;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.Record;
import com.jigsaw.config.AppConst;
import com.jigsaw.model.base.BaseSiteUser;
import com.jigsaw.tool.Str2MD5;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SiteUser extends BaseSiteUser<SiteUser> {
	public static final SiteUser dao = new SiteUser();
	
	public String currentLoginName = "";
	public String authServer = "";
	
	private String defaultPassword = "a111111";
	
	//通过 Model 修改/添加/删除 数据库
	public void testOperateUser(){
		String md5Pwd = Str2MD5.MD5(defaultPassword, 16);
		dao.set("RealName", "李良").set("PassWord", md5Pwd).save();
		
		dao.deleteById(1760);
		
		dao.findById(1753).set("MobilePhone", "13511112222").update();
		
		SiteUser user = SiteUser.dao.findByIdLoadColumns(1755, "RealName, LoginName");
		
		String userRealName = user.getStr("RealName");
		String loginName = user.getStr("LoginName");
		
		List<SiteUser> users = SiteUser.dao.find("SELECT * FROM Site_User WHERE UserID <= 20");
		
		Page<SiteUser> userPage = SiteUser.dao.paginate(1, 10, "SELECT *", "FROM Site_User WHERE UserID <= ?", 100);
		if(userPage.isFirstPage()){
			
		}
		
	}
	
	//通过 Db + Record 修改/添加/删除 数据库
	public void testOperateRecord(){
		String md5Pwd = Str2MD5.MD5(defaultPassword, 16);
		Record user = new Record().set("RealName", "James.Lee").set("PassWord", md5Pwd);
		Db.save("Site_User", user);
		
		Db.deleteById("Site_User", "UserID", 1894);
		
		user = Db.findById("Site_User", "UserID", 1895).set("LoginName", "James");
		Db.update("Site_User", "UserID", user);
		
		String loginName = user.getStr("LoginName");
		String passWrod = user.getStr("PassWord");
		
		List<Record> users = Db.find("SELECT * FROM Site_User WHERE UserID <= 20");
		
		Page<Record> userPage = Db.paginate(1, 10, "SELECT *", "FROM Site_User WHERE UserID <= ?", 100);
		if(userPage.isFirstPage()){
			String a = "22";
		}
	}
	
	public String testOperateTransaction(){
		//事务处理
		boolean succeed = Db.tx(new IAtom() {
			
			@Override
			public boolean run() throws SQLException {
				// 表 Site_User 的引擎是 InnoDB 才能使用事务
				int count = Db.update("UPDATE Site_User SET LoginName = 'abcc' WHERE UserID = ?", 1895);
				//count = 1
				int count2 = Db.update("UPDATE Site_User SET LoginName = 'def' WHERE UserID = ?", 1894);
				//count2 = 0
				//如果 表Site_User 的引擎是 MyISAM 则，第一条执行成功了；第二条未找到。
				return count == 1 && count2 == 1;
			}
		});
		
		if(succeed)
			return "success";
		else
			return "failed";
	}
	
	public SiteUser signIn(String loginName, String password){
		String sql = String.format("SELECT * FROM Site_User WHERE (LoginName = '%s' OR MobilePhone = '%s' OR Email = '%s')", loginName, loginName, loginName);
		List<SiteUser> users = dao.find(sql);
		if(users.size() >= 1){
			SiteUser user = users.get(0);
			
			boolean isFailedLock = false;
			PassportUseraccesslog log = (new PassportUseraccesslog()).getAccessLog(user.getUserID());
			if(log != null && log.getFailedPasswordAttemptCount() > 0){
				Date now = new Date();
				if(log.getFailedPasswordAttemptCount() > AppConst.LOGIN_FAIL_PWD_MAX_TIME
						&& ((new Date()).getTime() - log.getFailedPasswordAttemptStart().getTime())/(1000*60) <= AppConst.LOGIN_FAIL_PWD_LOCK_PERIOD){
					isFailedLock = true;
				}
			}
			
			String pwd = Str2MD5.MD5(password, 16);
			if(user.getPassWord().equals(pwd)){
				if(user.getStatus() == 0){
					//抛出用户状态异常
					//throw
				}else {
					(new PassportUseraccesslog()).dao.saveAccessSucceedLog(user.getUserID());
					return user;
				}
			}else {
				if(!isFailedLock){
					(new PassportUseraccesslog()).dao.saveAccessFailLog(user.getUserID());
					//用户名或密码错误
					//throw
				}else {
					//超过：规定的时间内尝试过多次数
					//throw new Exception();
				}
			}
		}
		return null;
	}
}
