package com.jigsaw.model;

import com.jigsaw.model.base.BaseSiteUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SiteUser extends BaseSiteUser<SiteUser> {
	public static final SiteUser dao = new SiteUser();
}
